<?php

namespace ForumBundle\Repository;

/**
 * fuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fuserRepository extends \Doctrine\ORM\EntityRepository
{
}
